sudo: required
language: generic

env:
- TCL_VERSION=8.5.0

addons:
  apt:
    packages:
    - tcl8.5
    - tk8.5
    - tcl8.5-dev
    - tk8.5-dev

install:

before_script:
        - export OOMMF_PREFIX=${OOMMF_PREFIX:-$HOME}
        - bash -x .travis/install-oommf.sh
	- OOMMF_PATH=/home/travis/oommf

# command to run tests
script:
#        - make test-without-run-oommf
- which tclsh
- which oommf
- $OOMMF_PATH/oommf.tcl +platform
