sudo: required
language: python
python:
        - "2.7"
# command to install dependencies

addons:
  apt:
    packages:
    - tcl8.6
    - tk8.6
    - tcl8.6-dev
    - tk8.6-dev

install:

before_script:
        - bash .travis/install-oommf.sh
        - export OOMMF_PREFIX=${OOMMF_PREFIX:-$HOME}

# command to run tests
script:
        - make test-without-run-oommf
