sudo: required
language: generic

env:
- TCL_VERSION=8.6.0

addons:
  apt:
    packages:
    - tcl8.6
    - tk8.6
    - tcl8.6-dev
    - tk8.6-dev

install:

before_script:
        - bash .travis/install-oommf.sh
        - export OOMMF_PREFIX=${OOMMF_PREFIX:-$HOME}

# command to run tests
script:
        - make test-without-run-oommf
