sudo: required
language: generic

env:
- TCL_VERSION=8.5.0

addons:
  apt:
    packages:
    - tcl8.5
    - tk8.5
    - tcl8.5-dev
    - tk8.5-dev

install:

before_script:
        - bash .travis/install-oommf.sh
        - export OOMMF_PREFIX=${OOMMF_PREFIX:-$HOME}

# command to run tests
script:
        - make test-without-run-oommf
